let terror_group = [
  {
    "Name": "Islamic State of Iraq and the Levant (ISIL)",
    "Active": "1999 — present",
    "Ideology": "Salafism, Salafi jihadism",
    "Flag": "Islamic State of Iraq and the Levant (ISIL).png",
    "Source": "https://en.wikipedia.org/wiki/Islamic_State_of_Iraq_and_the_Levant",
    "Summary": "The Islamic State of Iraq and the Levant (ISIL /ˈaɪsəl, ˈaɪsɪl/), also known as the Islamic State of Iraq and Syria (ISIS /ˈaɪsɪs/) officially as the Islamic State (IS) and by its Arabic language acronym Daesh (Arabic: داعش‎, translit. dāʿish, IPA: [ˈdaːʕɪʃ]) is a Salafi jihadist militant group and former unrecognised proto-state that follows a fundamentalist, Salafi doctrine of Sunni Islam. ISIL gained global prominence in early 2014 when it drove Iraqi government forces out of key cities in its Western Iraq offensive, followed by its capture of Mosul and the Sinjar massacre. The group has been designated a terrorist organisation by the United Nations and many individual countries. ISIL is widely known for its videos of beheadings and other types of executions of both soldiers and civilians, including journalists and aid workers, and its destruction of cultural heritage sites. The United Nations holds ISIL responsible for human rights abuses and war crimes. ISIL also committed ethnic cleansing on an historic scale in northern Iraq.ISIL originated as Jama'at al-Tawhid wal-Jihad in 1999, which pledged allegiance to al-Qaeda and participated in the Iraqi insurgency following the 2003 invasion of Iraq by Western forces at the behest of the United States. In June 2014 the group proclaimed itself a worldwide caliphate and began referring to itself as the Islamic State (الدولة الإسلامية ad-Dawlah al-Islāmiyah; IS). As a caliphate, it claimed religious, political and military authority over all Muslims worldwide. Its adoption of the name Islamic State and its idea of a caliphate have been widely criticised, with the United Nations, various governments and mainstream Muslim groups rejecting its statehood.In Syria, the group conducted ground attacks on both government forces and opposition factions and by December 2015, it held a large area extending from western Iraq to eastern Syria, containing an estimated 8 to 12 million people, where it enforced its interpretation of sharia law. ISIL is believed to be operational in 18 countries across the world, including Afghanistan and Pakistan, with ‘aspiring branches’ in Mali, Egypt, Somalia, Bangladesh, Indonesia and the Philippines. In 2015, ISIL was estimated to have an annual budget of more than US$1 billion and a force of more than 30,000 fighters."
  },
  {
    "Name": "Taliban",
    "Active": "1994 — present",
    "Ideology": "Deobandi fundamentalism, Pashtunwali, Religious nationalism",
    "Flag": "Taliban.png",
    "Source": "https://en.wikipedia.org/wiki/Taliban",
    "Summary": "The Taliban (Pashto: طالبان‎, ṭālibān ‘students’) or Taleban, who refer to themselves as the Islamic Emirate of Afghanistan (IEA), are a Sunni Islamic fundamentalist political movement and military organization in Afghanistan currently waging war (an insurgency, or jihad) within that country. Since 2016, the Taliban's leader is Mawlawi Hibatullah Akhundzada. The leadership is based in Quetta, Pakistan. From 1996 to 2001, the Taliban held power over roughly three quarters of Afghanistan, and enforced there a strict interpretation of Sharia, or Islamic law. The Taliban emerged in 1994 as one of the prominent factions in the Afghan Civil War and largely consisted of students (talib) from the Pashtun areas of eastern and southern Afghanistan who had been educated in traditional Islamic schools, and fought during the Soviet–Afghan War. Under the leadership of Mohammed Omar, the movement spread throughout most of Afghanistan, sequestering power from the Mujahideen warlords. The Islamic Emirate of Afghanistan was established in 1996 and the Afghan capital was transferred to Kandahar. It held control of most of the country until being overthrown after the American-led invasion of Afghanistan in December 2001 following the September 11 attacks. At its peak, formal diplomatic recognition of the Taliban's government was acknowledged by only three nations: Pakistan, Saudi Arabia, and the United Arab Emirates. The group later regrouped as an insurgency movement to fight the American-backed Karzai administration and the NATO-led International Security Assistance Force (ISAF) in the War in Afghanistan. The Taliban have been condemned internationally for the harsh enforcement of their interpretation of Islamic Sharia law, which has resulted in the brutal treatment of many Afghans, especially women. During their rule from 1996 to 2001, the Taliban and their allies committed massacres against Afghan civilians, denied UN food supplies to 160,000 starving civilians and conducted a policy of scorched earth, burning vast areas of fertile land and destroying tens of thousands of homes. According to the United Nations, the Taliban and their allies were responsible for 76% of Afghan civilian casualties in 2010, 80% in 2011, and 80% in 2012. Taliban has also engaged in cultural genocide, destroying numerous monuments including the famous 1500-year old Buddhas of Bamiyan."
  },
  {
    "Name": "Boko Haram",
    "Active": "2002 – present",
    "Ideology": "Wahhabism, Salafi jihadism",
    "Flag": "Boko Haram.png",
    "Source": "https://en.wikipedia.org/wiki/Boko_Haram",
    "Summary": "The Islamic State in West Africa or the Islamic State's West Africa Province (abbreviated as ISWA or ISWAP), formerly known as Jamā'at Ahl as-Sunnah lid-Da'wah wa'l-Jihād (Arabic: جماعة أهل السنة للدعوة والجهاد‎, ‘Group of the People of Sunnah for Preaching and Jihad’) and commonly known as Boko Haram until March 2015, is a jihadist terrorist organization based in northeastern Nigeria, also active in Chad, Niger and northern Cameroon. Founded by Mohammed Yusuf in 2002, the group has been led by Abubakar Shekau since 2009. When Boko Haram first formed, their actions were nonviolent. Their main goal was to ‘purify Islam in northern Nigeria.’ From March 2015 to August 2016, the group was aligned with the Islamic State of Iraq and the Levant. Since the current insurgency started in 2009, Boko Haram has killed tens of thousands and displaced 2.3 million from their homes and was ranked as the world's deadliest terror group by the Global Terrorism Index in 2015. After its founding in 2002, Boko Haram's increasing radicalisation led to the suppression operation by the Nigerian military forces and the summary execution of its leader Mohammed Yusuf in July 2009. Its unexpected resurgence, following a mass prison break in September 2010, was accompanied by increasingly sophisticated attacks, initially against soft targets, but progressing in 2011 to include suicide bombings of police buildings and the United Nations office in Abuja. The government's establishment of a state of emergency at the beginning of 2012, extended in the following year to cover the entire northeast of Nigeria, led to an increase in both security force abuses and militant attacks."
  },
  {
    "Name": "Al-Qaida",
    "Active": "1988 – present",
    "Ideology": "Wahhabism, Salafist jihadism, Qutbism, Pan-Islamism, Anti-Communism, Anti-Zionism, Antisemitism",
    "Flag": "Al-Qaida.png",
    "Source": "https://en.wikipedia.org/wiki/Al-Qaeda",
    "Summary": "Al-Qaeda (/ælˈkaɪdə, ˌælkɑːˈiːdə/; Arabic: القاعدة‎ al-Qāʿidah, IPA: [ælqɑːʕɪdɐ], translation: ‘The Base’, ‘The Foundation’ or ‘The Database’, alternatively spelled al-Qaida and al-Qa'ida) is a militant Sunni Islamist multi-national organization founded in 1988 by Osama bin Laden, Abdullah Azzam, and several other Arab volunteers during the Soviet invasion of Afghanistan. Al-Qaeda operates as a network of Islamic extremists and Salafist jihadists. The organization has been designated as a terrorist group by the United Nations Security Council, the North Atlantic Treaty Organization (NATO), the European Union, the United States, the United Kingdom, Russia, India, and various other countries (see below). Al-Qaeda has mounted attacks on non-military and military targets in various countries, including the 1998 United States embassy bombings, the September 11 attacks, and the 2002 Bali bombings. The United States government responded to the September 11 attacks by launching the ‘War on Terror’, which sought to undermine al-Qaeda and its allies. The deaths of key leaders, including that of Osama bin Laden, have led al-Qaeda's operations to shift from the top down organization and planning of attacks, to the planning of attacks which are carried out by associated groups and lone-wolf operators. Al-Qaeda characteristically employs attacks which include suicide attacks and the simultaneous bombing of several targets. Activities which are ascribed to al-Qaeda involve the actions of those who have made a pledge of loyalty to bin Laden, or to the actions of ‘al-Qaeda-linked’ individuals who have undergone training in one of its camps in Afghanistan, Pakistan, Iraq or Sudan. Al-Qaeda ideologues envision the removal of all foreign influences in Muslim countries, and the creation of a new caliphate ruling over the entire Muslim world. Among the beliefs ascribed to al-Qaeda members is the conviction that a Christian–Jewish alliance is conspiring to destroy Islam. As Salafist jihadists, members of al-Qaeda believe that the killing of non-combatants is religiously sanctioned. This belief ignores the aspects of religious scripture which forbid the murder of non-combatants and internecine fighting. Al-Qaeda also opposes what it regards as man-made laws, and wants to replace them with a strict form of sharia law."
  },
  {
    "Name": "Liberation Tigers of Tamil Eelam (LTTE)",
    "Active": "1976 – 2009",
    "Ideology": "Tamil nationalism, Separatism, Revolutionary socialism, Secularism",
    "Flag": "Liberation Tigers of Tamil Eelam (LTTE).jpg",
    "Source": "https://en.wikipedia.org/wiki/Liberation_Tigers_of_Tamil_Eelam",
    "Summary": "The Liberation Tigers of Tamil Eelam (Tamil: தமிழீழ விடுதலைப் புலிகள், translit. Tamiḻīḻa viṭutalaip pulikaḷ, Sinhalese: දෙමළ ඊළාම් විමුක්ති කොටි, translit. Demaḷa īḷām vimukti koṭi, commonly known as the LTTE or the Tamil Tigers) was a Tamil militant organization that was based in northeastern Sri Lanka. Founded in May 1976 by Velupillai Prabhakaran, it waged a secessionist nationalist insurgency to create an independent state of Tamil Eelam in the north and east of Sri Lanka for Tamil people. This campaign led to the Sri Lankan Civil War, which ran from 1983 until 2009, when the LTTE was eventually defeated during the presidency of Mahinda Rajapaksa. Due to its military victories, policies, call for national self-determination and constructive Tamil nationalist platform, the LTTE was supported by major sections of the Tamil community. University Teachers for Human Rights (Jaffna) claimed that ‘by combination of internal terror and narrow nationalist ideology the LTTE succeeded in atomizing the community. It took away not only the right to oppose but even the right to evaluate, as a community, the course they were taking. This gives a semblance of illusion that the whole society is behind the LTTE.’ At the height of its power, the LTTE possessed a well-developed militia and carried out many high-profile militant attacks, including the assassinations of key figures within the Sri Lankan government. The LTTE assassinated two world leaders: former Indian Prime Minister Rajiv Gandhi in 1991 and Sri Lankan President Ranasinghe Premadasa in 1993. The LTTE utilized suicide belts and pioneered the use of women in suicide attacks. It also acquired and used light aircraft in some of its attacks. Velupillai Prabhakaran headed the organisation from its inception until his death in 2009. The LTTE was proscribed as a terrorist organisation by 32 countries, including the European Union, Canada, the United States, and India."
  },
  {
    "Name": "Al-Shabaab",
    "Active": "2006 – present",
    "Ideology": "Salafi jihadism, Wahhabism, Islamism, Anti-Zionism, Antisemitism",
    "Flag": "Al-Shabaab.png",
    "Source": "https://en.wikipedia.org/wiki/Al-Shabaab_(militant_group)",
    "Summary": "Harakat al-Shabaab al-Mujahideen (HSM; Arabic: حركة الشباب المجاهدين‎, Ḥarakat ash-Shabāb al-Mujāhidīn; Somali: Xarakada Mujaahidiinta Alshabaab, lit. ‘Mujahideen Youth Movement’ or ‘Movement of Striving Youth’), more commonly known as al-Shabaab (/ælʃəˈbɑːb/; Arabic: الشباب‎, lit. '‘The Youth’ or ‘The Youngsters’, but can be translated as ‘The Guys’'), is a jihadist fundamentalist group based in East Africa. In 2012, it pledged allegiance to the militant Islamist organization Al-Qaeda. In February 2012, some of the group's leaders quarreled with Al-Qaeda over the union, and quickly lost ground. Al-Shabaab's troop strength was estimated at 7,000 to 9,000 militants in 2014. As of 2015, the group has retreated from the major cities, however al-Shabaab still controls large parts of the rural areas. Al-Shabaab began as the armed wing of the Islamic Courts Union (ICU), which later splintered into several smaller factions after its defeat in 2006 by Somalia's Transitional Federal Government (TFG) and the TFG's Ethiopian military allies. The group describes itself as waging jihad against ‘enemies of Islam’, and is engaged in combat against the Federal Government of Somalia and the African Union Mission to Somalia (AMISOM). Al-Shabaab has been designated as a terrorist organization by Australia, Canada, the United Arab Emirates, the United Kingdom and the United States. As of June 2012, the US State Department has open bounties on several of the group's senior commanders. In early August 2011, the Transitional Federal Government's troops and their AMISOM allies managed to capture all of Mogadishu from the al-Shabaab militants. An ideological rift within the group's leadership also emerged, and several of the organization's senior commanders were assassinated. Due to its Wahhabi roots, al-Shabaab is hostile to Sufi traditions and has often clashed with the militant Sufi group Ahlu Sunna Waljama'a. The group has also been suspected of having links with Al-Qaeda in Islamic Maghreb and Boko Haram. It attracted some members from western countries, including Samantha Lewthwaite and Abu Mansoor Al-Amriki."
  },
  {
    "Name": "Tehrik-i-Taliban Pakistan (TTP)",
    "Active": "2007 – present",
    "Ideology": "Deobandi fundamentalism",
    "Flag": "Tehrik-i-Taliban Pakistan (TTP).png",
    "Source": "https://en.wikipedia.org/wiki/Tehrik-i-Taliban_Pakistan",
    "Summary": "Tehrik-i-Taliban Pakistan (TTP; Urdu: تحریک طالبان پاکستان‎, ‘Taliban Movement of Pakistan’), alternatively referred to as the Taliban, is an Islamic armed group which is an umbrella organization of various militant groups based in the Khyber Pakhtunkhwa province along the Afghan border in Pakistan. Most Taliban groups in Pakistan coalesce under the TTP. In December 2007 about 13 groups united under the leadership of Baitullah Mehsud to form the Tehrik-i-Taliban. Among the Tehrik-i-Taliban stated objectives are resistance against the Pakistani state, Pakistani army, enforcement of their interpretation of sharia and a plan to unite against NATO-led forces in Afghanistan. The TTP is not directly affiliated with the Afghan Taliban movement led by Haibatullah Akhundzada, with both groups differing greatly in their histories, strategic goals and interests although they are both predominantly Pashtun. The Afghan Taliban, with the alleged support of Pakistani Taliban, operate against international coalition and Afghan security forces in Afghanistan but are strictly opposed to targeting the Pakistani state. The TTP in contrast has almost exclusively targeted elements of the Pakistani state although it took credit for the 2009 Camp Chapman attack and the 2010 Times Square car bombing attempt. Maulana Fazlullah became the group's new leader in late 2013. In the following year the TTP fragmented into at least four groups, with the defections said to have left the group in considerable disarray. Following Maulana Fazlullah's death by an American drone strike in Kunar province, Afghanistan, the TTP appointed Mufti Noor Wali Mehsud as the group's new emir."
  },
  {
    "Name": "Al-Qaida in Iraq",
    "Active": "2004 – 2006",
    "Ideology": "Salafi jihadism",
    "Flag": "Al-Qaida in Iraq.png",
    "Source": "https://en.wikipedia.org/wiki/Tanzim_Qaidat_al-Jihad_fi_Bilad_al-Rafidayn",
    "Summary": "Tanzim Qaidat al-Jihad fi Bilad al-Rafidayn or TQJBR (‘Organization of Jihad's Base in Mesopotamia’, Arabic: تنظيم قاعدة الجهاد في بلاد الرافدين‎, translit. tanẓīm qā‘idat al-jihād fī bilād ar-rāfidayn), also referred to as Al-Qaeda in Iraq, AQI, or Al-Qaeda in Mesopotamia) was an Iraqi Sunni Islamic Jihadist organization affiliated with al-Qaeda, for part of the first two decades of the 21st century. The group was founded by the Jordanian militant Abu Musab al-Zarqawi in 1999 under the name Jama'at al-Tawhid wal-Jihad (Arabic: جماعة التوحيد والجهاد, ‘Group of Monotheism and Jihad’). The group is believed to have started bomb attacks in Iraq as of August 2003, five months after the coalition invasion and occupation of Iraq, targeting UN representatives, Iraqi Shiite institutions, the Jordanian embassy, provisional Iraqi government institutions. After it pledged allegiance to Osama bin Laden's al-Qaeda network in October 2004, its official name became Tanzim Qaidat al-Jihad fi Bilad al-Rafidayn."
  },
  {
    "Name": "Shining Path (SL)",
    "Active": "late 1960s - present",
    "Ideology": "Communism, Marxism–Leninism–Maoism, Anti-revisionism, Gonzalo Thought",
    "Flag": "Shining Path (SL).png",
    "Source": "https://en.wikipedia.org/wiki/Shining_Path",
    "Summary": "The Communist Party of Peru – Shining Path (Spanish: Partido Comunista del Perú - Sendero Luminoso), more commonly known as the Shining Path (Spanish: Sendero Luminoso), is a communist revolutionary organization in Peru, espousing Marxism-Leninism-Maoism. When it first launched the internal conflict in Peru in 1980, its goal was to overthrow the state by guerrilla warfare and replace it with a ‘New Democracy’. The Shining Path believed that by establishing a dictatorship of the proletariat, inducing a cultural revolution, and eventually sparking a world revolution, they could arrive at full communism. Their representatives stated that existing socialist countries were revisionist, and the Shining Path was the vanguard of the world communist movement. The Shining Path's ideology and tactics have been influential among other Maoist insurgent groups, notably the Communist Party of Nepal (Maoist Centre) and other Revolutionary Internationalist Movement-affiliated organizations. Widely condemned for its brutality, including violence deployed against peasants, trade union organizers, elected officials and the general civilian population, the Shining Path is regarded by Peru as a terrorist organization. Japan, the United States, the European Union, and Canada likewise classify the group as a terrorist organization and prohibit funding and other financial support. Since the capture of its leader Abimael Guzmán in 1992, the Shining Path has declined in activity. The common name of this group, Shining Path, distinguishes it from several other Peruvian communist parties with similar names (see Communism in Peru). The name is derived from a maxim of José Carlos Mariátegui, the founder of the original Peruvian Communist Party in the 1920s: ‘El Marxismo-Leninismo abrirá el sendero luminoso hacia la revolución’ (‘Marxism–Leninism will open the shining path to revolution’)."
  },
  {
    "Name": "Farabundo Marti National Liberation Front (FMLN)",
    "Active": "1980 - present",
    "Ideology": "Socialism, Syndicalism, Historicall, Marxism–Leninism",
    "Flag": "Farabundo Marti National Liberation Front (FMLN).png",
    "Source": "https://en.wikipedia.org/wiki/Farabundo_Mart%C3%AD_National_Liberation_Front",
    "Summary": "The Farabundo Martí National Liberation Front (in Spanish: Frente Farabundo Martí para la Liberación Nacional, FMLN) is one of the two major political parties in El Salvador. On March 15, 2009, the FMLN won the presidential elections with former journalist Mauricio Funes as its candidate. Two months earlier in municipal and legislative elections, the FMLN won the majority of the mayoralties in the country and a plurality of the National Assembly seats. Tensions began to build between the farmers and the elite class in the time leading up to the Salvadoran Civil War including political assassinations by the El Salvadoran government on outspoken critics starting in the early 1970s. In 1979, farmers went on strike for higher wages and better working conditions on Hacienda California, a large farm in Tierra Blanca. Due to this strike National Guard troops responded to the growing violence in Tierra Blanca using military force. As the violence spread into the residential areas of El Salvador, animosity heightened between the campesinos and the elite class. The previously politically withdrawn campesinos began to join the FMLN and other left-wing guerrilla groups. On December 17, 1979, in period of national crisis, the three dominant organizations (FPL, RN and PCS) of the Salvadoran left formed the Coordinadora Político-Militar. The CPM's first manifesto was released on January 10, 1980, and the day after, the Coordinadora Revolucionaria de Masas was formed as a union of revolutionary mass organizations. CRM later merged with the Frente Democrático Salvadoreño to form the Frente Democrático Revolucionario. It is alleged by the United States that some credit for the unity of the five organizations that formed the FMLN may belong to Cuba's Fidel Castro, who facilitated negotiation between the groups in Havana in December 1979. However, neither the Cuban nor Soviet government were significantly responsible for forming FMLN, although it received some of its arms and supplies from the Soviet Union and Cuba. While all five groups called themselves revolutionaries and socialists, they had serious ideological and practical differences, and there had been serious conflicts, even including in some cases bloodshed, between some of the groups during the 1970s."
  },
  {
    "Name": "Revolutionary Armed Forces of Colombia (FARC)",
    "Active": "1964 – 2017",
    "Ideology": "Marxism–Leninism, Guevarism, Bolivarianism, Revolutionary socialism, Left-wing nationalism, Foco theory",
    "Flag": "Revolutionary Armed Forces of Colombia (FARC).png",
    "Source": "https://en.wikipedia.org/wiki/Revolutionary_Armed_Forces_of_Colombia",
    "Summary": "The Revolutionary Armed Forces of Colombia—People's Army (Spanish: Fuerzas Armadas Revolucionarias de Colombia—Ejército del Pueblo, FARC–EP and FARC) was a guerrilla movement involved in the continuing Colombian armed conflict from 1964 to 2017. It was known to employ a variety of military tactics in addition to more unconventional methods, including terrorism. The FARC–EP was formed during the Cold War period as a Marxist–Leninist peasant force promoting a political line of agrarianism and anti-imperialism. The operations of the FARC–EP were funded by kidnap and ransom; illegal mining; extortion or taxation of various forms of economic activity and the taxation, production and distribution of illegal drugs. The United Nations has estimated that 12% of all killings of civilians in the Colombian conflict were committed by FARC and National Liberation Army (ELN) guerrillas, with 80% committed by right-wing paramilitaries, and the remaining 8% committed by Colombian security forces. The strength of the FARC–EP forces were high; in 2007, the FARC said they were an armed force of 18,000 men and women; in 2010, the Colombian military calculated that FARC forces consisted of about 13,800 members, 50 percent of whom were armed guerrilla combatants; and, in 2011, the President of Colombia, Juan Manuel Santos, said that FARC–EP forces comprised fewer than 10,000 members. In 2013 it was reported that 26,648 FARC and ELN members had decided to demobilize since 2002. According to a report from Human Rights Watch in 2006, approximately 20–30% of the recruits were minors, some of whom were forced to join the FARC, while women comprise around 40 percent of the guerilla army. The greatest concentrations of FARC forces were in the southeastern, northern and southwestern regions of Colombia's 500,000 square kilometers (190,000 sq mi) of jungle, in the plains at the base of the Andean mountain chain and in northwestern Colombia.However, the FARC and the ELN lost control of much of the territory, especially in urban areas, forcing them to relocate to remote areas in the jungle and the mountains."
  },
  {
    "Name": "Kurdistan Workers' Party (PKK)",
    "Active": "1978 - present",
    "Ideology": "Kurdish nationalism, Communalism, Democratic confederalism, Libertarian socialism, Jineology, Anti-capitalism",
    "Flag": "Kurdistan Workers' Party (PKK).png",
    "Source": "https://en.wikipedia.org/wiki/Kurdistan_Workers%27_Party",
    "Summary": "The Kurdistan Workers' Party or PKK (Kurdish: Partiya Karkerên Kurdistanê‎) is a Kurdish far-left militant and political organization based in Turkey and Iraq. Since 1984 the PKK has been involved in an armed conflict with the Turkish state (with a two-year cease-fire during 2013–2015), with the initial aim of achieving an independent Kurdish state, later changing it to a demand for equal rights and Kurdish autonomy in Turkey. The group was founded in 1978 in the village of Fis (near Lice) by a group of Kurdish students led by Abdullah Öcalan. The PKK's ideology was originally a fusion of revolutionary socialism and Kurdish nationalism, seeking the foundation of an independent Communist state in the region, which was to be known as Kurdistan. The initial reasons given by the PKK for this were the oppression of Kurds in Turkey and Capitalism. By then, the use of Kurdish language, dress, folklore, and names were banned in Kurdish-inhabited areas. The words ‘Kurds’, ‘Kurdistan’, or ‘Kurdish’ were officially banned by the Turkish government temporarily. Following the military coup of 1980, the Kurdish language was officially prohibited in public and private life. Many who spoke, published, or sang in Kurdish were arrested and imprisoned. The PKK was then formed, as part of a growing discontent over the suppression of Turkey's ethnic Kurds, in an effort to establish linguistic, cultural, and political rights for Turkey's ethnic Kurdish minority. Since the PKK's foundation, it has been involved in armed clashes with Turkish security forces. The full-scale insurgency, however, did not begin until 15 August 1984, when the PKK announced a Kurdish uprising. Since the conflict began, more than 40,000 have died, most of whom were Turkish Kurdish civilians."
  },
  {
    "Name": "New People's Army (NPA)",
    "Active": "1969 - present",
    "Ideology": "Marxism – Leninism – Maoism",
    "Flag": "New People's Army (NPA).png",
    "Source": "https://en.wikipedia.org/wiki/New_People%27s_Army",
    "Summary": "The New People's Army (NPA) (Filipino: Bagong Hukbong Bayan) is the armed wing of the Communist Party of the Philippines (CPP). It was formed and founded by Jose Maria Sison, Bernabe Buscayno, and Lucio Manlapaz on 29 March 1969. The Maoist NPA conducts its armed guerrilla struggle based on the strategical line of protracted people's war. With an estimated strength of nearly 3,200 militants in 2015, and latest attack as recent as 2015 in Agusan Del Sur, it operates in the rural areas throughout Philippines especially in the inaccessible hill areas of provinces far from the major cities. The NPA collect taxes, mostly from businesses, in the areas where it operates. The CPP refers to the NPA as ‘the tax enforcement agency of the people's revolutionary government’. ‘Revolutionary taxes are used to fund community services and never go to the pockets of corrupt leaders’ said National Democratic Front (NDF) spokesperson, Fidel Agcaoili. Peace negotiations have reached an impasse. The Philippine government has specifically drafted a ‘new framework’ which seeks to end the 27-year-long stalemate in the talks, hoping to build ground with the leftist rebels that is more comprehensive than human rights, the only issue on which the negotiating parties agree. The NDF wants the Comprehensive Agreement on Socio-Economic Reforms (CASER) signed first before the bilateral ceasefire agreement, or both can be signed simultaneously."
  },
  {
    "Name": "Nicaraguan Democratic Force (FDN)",
    "Active": "1981 - present",
    "Ideology": "Democratism, Anti-communism",
    "Flag": "Nicaraguan Democratic Force (FDN).png",
    "Source": "https://en.wikipedia.org/wiki/Nicaraguan_Democratic_Force",
    "Summary": "The Nicaraguan Democratic Force (Fuerza Democrática Nicaragüense, or FDN) was one of the earliest Contra groups, formed on August 11, 1981 in Guatemala City. It was formed to oppose Nicaragua's revolutionary Sandinista government following the 1979 overthrow of Anastasio Somoza Debayle. It merged the 15th of September Legion, which comprised mostly former members of Somoza's National Guard, with the Nicaraguan Democratic Union, an organization of émigrés from the business and professional classes. The new FDN also began assimilating the MILPAS movement, bands led by disenchanted former MAP-ML guerrillas. The FDN military was under the command of former National Guard colonel Enrique Bermúdez. The FDN was heavily backed by the Central Intelligence Agency and the Reagan administration. The FDN's political leadership was based in Miami, Florida, though critics always questioned how much control the political wing truly had over the military forces. Originally, the head of the UDN, José Francisco Cardenal, also assumed political leadership of the new FDN, along with Mariano Mendoza and Aristides Sánchez. However, by autumn 1982 he had alienated both the FDN's military command and its Miami political executive committee, as well as the Argentine advisors."
  },
  {
    "Name": "Al-Qaida in the Arabian Peninsula (AQAP)",
    "Active": "January 2009 – present",
    "Ideology": "	Salafism, Salafist jihadism, Anti-Zionism, Antisemitism, Qutbism",
    "Flag": "Al-Qaida in the Arabian Peninsula (AQAP).png",
    "Source": "https://en.wikipedia.org/wiki/Al-Qaeda_in_the_Arabian_Peninsula",
    "Summary": "Al-Qaeda in the Arabian Peninsula (Arabic: تنظيم القاعدة في جزيرة العرب‎, translit. Tanẓīm al-Qā‘idah fī Jazīrat al-‘Arab, lit. 'al-Qaeda Organization in the Arabian Peninsula' or تنظيم قاعدة الجهاد في جزيرة العرب‎, Tanẓīm Qā‘idat al-Jihād fī Jazīrat al-‘Arab, ‘Organization of Jihad's Base in the Arabian Peninsula’), or AQAP, also known as Ansar al-Sharia in Yemen (Arabic: جماعة أنصار الشريعة‎, Jamā‘at Anṣār ash-Sharī‘ah, ‘Group of the Helpers of the Sharia’), is a militant Islamist organization, primarily active in Yemen and Saudi Arabia. It was named for al-Qaeda, and states it is subordinate to that group and its now-deceased leader Osama bin Laden, a Saudi citizen of Yemeni heritage. It is considered the most active of al-Qaeda's branches, or ‘franchises,’ that emerged due to weakening central leadership. The U.S government believes AQAP to be the most dangerous al-Qaeda branch. The group established an emirate during the 2011 Yemeni Revolution, which waned in power after foreign interventions in the subsequent Yemeni Civil War. The group has been designated as a terrorist organization by the United Nations and several countries and international organizations. Since 2015, hundreds of AQAP members were recruited by militias backed by Saudi Arabia and the United Arab Emirates in the war against the Houthis. Like al-Qaeda Central, AQAP opposes the monarchy of the House of Saud. AQAP was formed in January 2009 from a merger of al-Qaeda's Yemeni and Saudi branches. The Saudi group had been effectively suppressed by the Saudi government, forcing its members to seek sanctuary in Yemen. In 2010, it was believed to have several hundred members. The group also seeks for the destruction of the Israeli state and the liberation of the Palestinian territories."
  },
  {
    "Name": "Houthi extremists (Ansar Allah)",
    "Active": "1994 – present",
    "Ideology": "Zaydi Revivalism, Anti-imperialism, Irredentism, Anti-Zionism, Antisemitism",
    "Flag": "Houthi extremists (Ansar Allah).png",
    "Source": "https://en.wikipedia.org/wiki/Houthi_movement",
    "Summary": "The Houthi movement (/ˈhuːθi/; Arabic: الحوثيون‎ al-Ḥūthiyyūn [ˈħuːθij.juːn]), officially called Ansar Allah (anṣār allāh أنصار الله ‘Supporters of God’), is an Islamic religious-political-armed movement that emerged from Sa'dah in northern Yemen in the 1990s. They are of the Zaidi sect, though the movement reportedly also includes Sunnis. Under the leadership of Hussein Badreddin al-Houthi, the group emerged as a Zaydi opposition to former Yemeni president Ali Abdullah Saleh, whom they charged with massive financial corruption and criticized for being backed by Saudi Arabia and the United States at the expense of the Yemeni people and Yemen's sovereignty. Resisting Saleh's order for his arrest, Hussein was killed in Sa'dah in 2004 along with a number of his guards by the Yemeni army, sparking the Houthi insurgency in Yemen. Since then, except for a short intervening period, the movement has been led by his brother Abdul-Malik al-Houthi. The Houthi movement attracts its Zaidi-Shia followers in Yemen by promoting regional political-religious issues in its media, including the overarching US-Israeli conspiracy and Arab ‘collusion’. In 2003, the Houthis' slogan ‘God is great, death to the US, death to Israel, curse the Jews, and victory for Islam’, became the group's trademark. Houthi officials, however, have rejected the literal interpretation of the slogan. The movement's expressed goals include combating economic underdevelopment and political marginalization in Yemen while seeking greater autonomy for Houthi-majority regions of the country. They also claim to support a more democratic non-sectarian republic in Yemen. The Houthis have made fighting corruption the centerpiece of their political program."
  },
  {
    "Name": "Islamic State of Iraq (ISI)",
    "Active": "2006 – 2013",
    "Ideology": "Salafism, Salafist jihadism, Wahhabism, Anti-Shi'ism",
    "Flag": "Islamic State of Iraq (ISI).jpg",
    "Source": "https://en.wikipedia.org/wiki/Islamic_State_of_Iraq",
    "Summary": "The Islamic State of Iraq (ISI; Arabic: دولة العراق الإسلامية‎ Dawlat al-ʿIrāq al-ʾIslāmiyyah) (commonly referred to as al-Qaeda in Iraq) was a militant Salafist jihadist group that aimed to establish an Islamic state in Sunni, Arab-majority areas of Iraq during the Iraq War and later in Syria during the Syrian Civil War. Islamic State of Iraq traces its origins to Jama'at al-Tawhid wal-Jihad, which was formed by the Jordanian national Abu Musab al-Zarqawi in Jordan in 1999. Al-Zarqawi led the group, under numerous name changes, until his death in June 2006. Jama'at participated in the Iraqi insurgency (2003–2011) following the 2003 invasion of Iraq by Western forces, and on 17 October 2004 al-Zarqawi had pledged allegiance to Osama bin Laden's al-Qaeda network; and the group became known as Tanzim Qaidat al-Jihad fi Bilad al-Rafidayn (commonly known as al-Qaeda in Iraq). In January 2006, Tanzim and five other Iraqi insurgent groups formed the Mujahideen Shura Council, which on 15 October 2006 merged to form Islamic State of Iraq. At their height in 2006–2008, ISI had military units or strongholds in Mosul and in the governorates of Baghdad, Al Anbar and Diyala, and they claimed Baqubah as their capital. The new group continued to be commonly referred to as al-Qaeda in Iraq. Shortly after al-Zarqawi's death, al-Qaeda in Iraq named a new leader, Abu-Hamzah al-Muhajir, thought to be a pseudonym, which the US military named as Abu Ayyub al-Masri, an Egyptian militant based in Baghdad. Al-Masri and ISI leader Abu Omar al-Baghdadi were killed during a military operation on a safehouse on 18 April 2010. Abu Omar al-Baghdadi was succeeded as leader of ISI by Abu Bakr al-Baghdadi. On 14 May 2010, al-Masri was succeeded by Abu Suleiman al-Naser (also known as al-Nasser Lideen Illah Abu Suleiman), who was in turn killed some time in 2011. Following Suleiman's death, the position of ‘War Minister’ was replaced by a Military Council composed of former regime military officers under the leadership of Haji Bakr."
  },
  {
    "Name": "Aum Shinri Kyo",
    "Active": "1984 - present",
    "Ideology": "Japanese new religious movement",
    "Flag": "Aum Shinri Kyo.jpg",
    "Source": "https://en.wikipedia.org/wiki/Aum_Shinrikyo",
    "Summary": "Aleph (Japanese: アレフ Hepburn: Arefu), formerly Aum Shinrikyo (オウム真理教 Oumu Shinrikyō), is a Japanese doomsday cult founded by Shoko Asahara in 1984. It carried out the deadly Tokyo subway sarin attack in 1995 and was found to have been responsible for another smaller sarin attack the previous year. The group never confessed. They claim that those who carried out attacks did so secretly, without being known to other executives and ordinary believers. Asahara broadcast his singing, insisting on his innocence through a radio broadcast relayed from Russia and directed toward Japan. On 6 July 2018, after exhausting all appeals, Asahara and six other followers were executed by Japan, as punishment for the 1995 attacks and other crimes. On 26 July 2018, the remaining six followers on death row were executed by Japan. At 12:10 am, on New Year's Day 2019, at least nine people were injured (one seriously) when a car was deliberately driven into crowds celebrating the new year on Takeshita Street in Tokyo. Local police reported the arrest of Kazuhiro Kusakabe, the suspected driver, who allegedly admitted to intentionally ramming his vehicle into crowds to protest his opposition to the death penalty, specifically in retaliation for the execution of the aforementioned Aum cult members. Aum Shinrikyo, which split into Aleph and Hikari no Wa in 2007, had already been formally designated a terrorist organization by several countries, including the European Union, Russia, Canada, Kazakhstan, and the United States."
  },
  {
    "Name": "Irish Republican Army (IRA)",
    "Active": "1969 – 2005",
    "Ideology": "National liberation war, Irish republicanism, Irish nationalism",
    "Flag": "Irish Republican Army (IRA).png",
    "Source": "https://en.wikipedia.org/wiki/Provisional_Irish_Republican_Army",
    "Summary": "The Irish Republican Army (IRA) (Irish: Óglaigh na hÉireann), also known as the Provisional Irish Republican Army (Provisional IRA or Provos) an Irish republican paramilitary organisation that sought to end British rule in Northern Ireland, facilitate the reunification of Ireland and bring about an independent republic encompassing all of Ireland. It was the biggest and most active republican paramilitary group during the Troubles. It saw itself as the successor to the original IRA and called itself simply the Irish Republican Army (IRA), or Óglaigh na hÉireann in Irish, and was broadly referred to as such by others. The IRA was designated an unlawful terrorist organisation in the United Kingdom and an unlawful organisation in the Republic of Ireland. The Provisional IRA emerged in December 1969, following a split in the republican movement. It was so-called to mirror the 1916 Provisional Government of the Irish Republic, and also to designate it as temporary pending reorganisation of the movement. Although this eventually happened in 1970, the name ‘Provisional’ stuck with them. The Troubles had begun shortly before when a largely Catholic, nonviolent civil rights campaign was met with violence from both Ulster loyalists and the Royal Ulster Constabulary (RUC), culminating in the August 1969 riots and deployment of British troops. The IRA initially focused on defence of Catholic areas, but it began an offensive campaign in 1971 (see timeline). The IRA's primary goal was to force the United Kingdom to negotiate a withdrawal from Northern Ireland. It used guerrilla tactics against the British Army and RUC in both rural and urban areas. It also carried out a bombing campaign in Northern Ireland and England against what it saw as political and economic targets."
  },
  {
    "Name": "Al-Nusrah Front",
    "Active": "2012 – 2017",
    "Ideology": "Salafism, Wahhabism, Salafist jihadism",
    "Flag": "Al-Nusrah Front.png",
    "Source": "https://en.wikipedia.org/wiki/Al-Nusra_Front",
    "Summary": "Al-Nusra Front or Jabhat al-Nusra (Arabic: جبهة النصرة‎), known as Jabhat Fatah al-Sham (Arabic: جبهة فتح الشام‎) after July 2016, and also described as al-Qaeda in Syria or al-Qaeda in the Levant, was a Salafist jihadist organization fighting against Syrian government forces in the Syrian Civil War. Its aim was to establish an Islamic state in the country. Formed in 2012, in November of that year The Washington Post described al-Nusra as ‘the most aggressive and successful’ of the rebel forces. In December 2012, the United States Department of State designated it a foreign terrorist organization, and in November 2013, it became the official Syrian branch of al-Qaeda. From 2012 to 2013, the al-Nusra Front's full name was the ‘Victory Front for the People of the Levant by the Mujahideen of the Levant on the Fields of Jihad’ (Arabic: جبهة النصرة لأهل الشام من مجاهدي الشام في ساحات الجهاد‎, transliteration: Jabhat an-Nuṣrah li-ahli ash-Shām min Mujahideen ash-Shām fi Sahat al-Jihad). In March 2015, the group joined with other jihadist groups to form the Army of Conquest. In July 2016, al-Nusra formally re-branded as Jabhat Fatah al-Sham (‘Front for the Conquest of the Levant’). On 28 January 2017, following violent clashes with Ahrar al-Sham and other rebel groups, Jabhat Fatah al-Sham merged with four other groups to become Hayat Tahrir al-Sham."
  },
  {
    "Name": "National Union for the Total Independence of Angola (UNITA)",
    "Active": "1966 - present",
    "Ideology": "Conservatism, Angolan nationalism, Christian democracy, Maoism",
    "Flag": "National Union for the Total Independence of Angola (UNITA).png",
    "Source": "https://en.wikipedia.org/wiki/UNITA",
    "Summary": "The National Union for the Total Independence of Angola (UNITA) (Portuguese: União Nacional para a Independência Total de Angola) is the second-largest political party in Angola. Founded in 1966, UNITA fought alongside the Popular Movement for the Liberation of Angola (MPLA) in the Angolan War for Independence (1961–1975) and then against the MPLA in the ensuing civil war (1975–2002). The war was one of the most prominent Cold War proxy wars, with UNITA receiving military aid from the United States and South Africa while the MPLA received support from the Soviet Union and its allies. UNITA was led by Jonas Savimbi from its foundation until his death in 2002. His successor as president of UNITA is Isaías Samakuva. Following Savimbi's death, UNITA abandoned armed struggle and participated in electoral politics. The party won 51 out of 220 seats in the 2017 parliamentary election. Jonas Savimbi and Antonio da Costa Fernandes founded UNITA on 13 March 1966 in Muangai in Moxico province in Portuguese Angola (during the Estado Novo regime). 200 other delegates were present in the event. UNITA launched its first attack on Portuguese colonial authorities on 25 December 1966. Savimbi was originally affiliated with Holden Roberto's National Liberation Front of Angola (FNLA). UNITA later moved to Jamba in Angola's southeastern province of Cuando Cubango. UNITA's leadership was drawn heavily from Angola's majority Ovimbundu ethnic group and its policies were originally Maoist, perhaps influenced by Savimbi's early training in China. They aimed at rural rights and recognized ethnic divisions. In later years, however, UNITA became more aligned with the United States, espousing support for capitalism in Angola."
  },
  {
    "Name": "Hutu extremists",
    "Active": "1994 - 2005",
    "Ideology": "Racist, Supremacist",
    "Flag": "Hutu extremists.jpg",
    "Source": "https://en.wikipedia.org/wiki/Hutu_Power",
    "Summary": "Hutu Power is a racist and supremacist ideology propounded by Hutu extremists in Rwanda. It led to the 1994 Rwandan genocide against the Tutsi. Hutu Power political parties and movements included the Akazu, the Coalition for the Defence of the Republic and its Impuzamugambi paramilitary militia, and the governing National Republican Movement for Democracy and Development and its Interahamwe paramilitary militia. Hassan Ngeze in 1990 created the Hutu Ten Commandments that served as the basis of Hutu Power ideology. The Commandments called for the supremacy of Hutus in Rwanda, calling for exclusive Hutu leadership over Rwanda's public institutions and public life, complete segregation of Hutus from Tutsis, and complete exclusion of Tutsis from public institutions and public life. Hutu Power ideology reviled Tutsis as outsiders bent on restoring a Tutsi-dominated monarchy, and idealized all things Hutu. The Commandments declared that any form of relationship between Hutus and Tutsi women was forbidden; and that any Hutu who ‘marries a Tutsi woman’, ‘befriends a Tutsi woman’, or ‘employs a Tutsi woman as a secretary or a concubine’ was a traitor to the Hutu people. It denounced Tutsis as dishonest in business whose ‘only aim is the supremacy of his ethnic group’; and declared that any Hutu who did business with a Tutsi was a traitor to the Hutu people. The Commandments declared that ‘The Hutu should stop having mercy on the Tutsi’ and referred to the Tutsis as ‘common Tutsi enemy’."
  },
  {
    "Name": "Sikh Extremists",
    "Active": "1940s - present",
    "Ideology": "Unknown",
    "Flag": "Sikh Extremists.jpg",
    "Source": "https://en.wikipedia.org/wiki/Khalistan_movement",
    "Summary": "The Khalistan movement is a Sikh separatist movement, which seeks to create a separate country called Khalistān (‘The Land of the Pure’) in the Punjab region to serve as a homeland for Sikhs. The territorial definition of the proposed country Khalistan consists of both the Punjab, India along with Punjab, Pakistan and includes parts of Haryana, Himachal Pradesh, Jammu and Kashmir, and Rajasthan. The Khalistan movement began as an expatriate venture. In 1971, the first explicit call for Khalistan was made in an advertisement published in the New York Times by an expat Jagjit Singh Chohan. With financial and political support of the Sikh diaspora the movement flourished in the Indian state of Punjab, which has a Sikh-majority population and reached its zenith in the late 1970s and 1980s, when the secessionist movement caused large-scale violence among the local population including assassination of PM Indira Gandhi and bombing of Air India plane killing 328 passengers. Various pro-Khalistan outfits have been involved in a separatist movement against the Government of India ever since. In the 1990s the insurgency petered out, and the movement failed to reach its objective due to multiple reasons including a heavy police crackdown on separatists, divisions among the Sikhs and loss of support from the Sikh population. The extremist violence had started with targeting of the Nirankaris and followed by attack on the government machinery and the Hindus. Ultimately the Sikh terrorists also targeted other Sikhs with opposing viewpoints. This led to further loss of public support and the militants were eventually brought under control of law enforcement agencies by 1993."
  },
  {
    "Name": "Khorasan Chapter of the Islamic State",
    "Active": "2015 – present",
    "Ideology": "Salafist Islamism, Salafist Jihadism",
    "Flag": "Khorasan Chapter of the Islamic State.png",
    "Source": "https://en.wikipedia.org/wiki/Islamic_State_of_Iraq_and_the_Levant_%E2%80%93_Khorasan_Province",
    "Summary": "The Islamic State of Iraq and the Levant – Khorasan Province (Arabic: الدولة الإسلامية في العراق والشام – ولاية خراسان‎, ad-Dawlah al-Islāmiyah fī 'l-ʿIrāq wa-sh-Shām – Wilayah Khorasan), or ISIL-KP, is a branch of the militant Islamist group Islamic State of Iraq and the Levant (ISIL), active in Afghanistan and Pakistan. Some media sources also use the terms ISK, ISISK, IS-KP, or ISIS-K in Ramlal kotr referring to the group. The Khorasan group's area of operations also includes other parts of South Asia, such as India where individuals have pledged allegiance to it. ISIL announced the group's formation in January 2015 and appointed former Tehrik-i-Taliban Pakistan militant Hafiz Saeed Khan as its leader, with former Afghan Taliban commander Abdul Rauf Aliza appointed as deputy leader. Aliza was killed in a U.S. drone strike in February 2015, while Khan was killed in a U.S. airstrike in July 2016. Around September 2014, ISIL sent representatives to Pakistan to meet with local militants, including some Tehrik-i-Taliban Pakistan (TTP) factions, following several months of discussions. At the same time, leaflets, flags and propaganda materials in support of ISIL began being distributed in parts of Pakistan, including a pamphlet written in Pashto and Dari that called on all Muslims to swear allegiance to Abu Bakr al-Baghdadi. The leaflets were believed to have been produced and distributed from across the border in Afghanistan. In October 2014, former Taliban commander Abdul Rauf Khadim visited Iraq.Later on he returned to Afghanistan where he recruited followers in Helmand and Farah provinces. In the same month, 6 TTP commanders in Pakistan; Hafiz Khan Saeed, official spokesman Shahidullah Shahid, and the TTP commanders of Kurram and Khyber tribal regions and Peshawar and Hangu Districts, publicly defected from the TTP and pledged allegiance to Abu Bakr al-Baghdadi."
  },
  {
    "Name": "Chechen Rebels",
    "Active": "1785 – present",
    "Ideology": "Unknown",
    "Flag": "Chechen Rebels.jpg",
    "Source": "https://en.wikipedia.org/wiki/Chechen%E2%80%93Russian_conflict",
    "Summary": "The Chechen–Russian conflict (Russian: Чеченский конфликт, Chechenskiy konflikt) is the centuries-long conflict, often armed, between the Russian (formerly Soviet) government and various Chechen forces. Formal hostilities date back to 1785, though elements of the conflict can be traced back considerably further. The Russian Empire initially had little interest in the North Caucasus itself other than as a communication route to its ally Georgia and its enemies, the Persian and Ottoman Empires, but growing tensions triggered by Russian activities in the region resulted in an uprising of Chechens against the Russian presence in 1785, followed by further clashes and the outbreak of the Caucasian War in 1817. Russia only succeeded in suppressing the Chechen rebels in 1864. During the Russian Civil War, Chechens and other Caucasian nations lived in independence for a few years before being Sovietized in 1921. During World War II, the Chechens saw the German invasion as an opportunity to revolt against the Soviet regime. In response, they were deported en masse to Central Asia where they were forced to stay until 1957. The most recent conflict between Chechen and the Russian government took place in the 1990s. As the Soviet Union disintegrated, the Chechen separatists declared independence in 1991. By late 1994 the First Chechen War broke out and after two years of fighting the Russian forces withdrew from the region. In 1999, the fighting restarted and concluded the next year with the Russian security forces establishing control over Chechnya."
  }
];
